services:
  backend:
    build:
      context: ./backend
    ports:
      - '4000:4000'
    volumes:
      - /app/node_modules
    command: npm run watch
    develop:
      watch:
        - action: sync
          path: ./backend/src
          target: /app/src
          ignore:
            - ./backend/node_modules/
        - action: rebuild
          path: ./backend/package.json
    environment:
      NODE_ENV: development
      JWT_SECRET: # write JWT secret key

  frontend:
    build:
      context: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - /app/node_modules
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
        - action: sync
          path: ./frontend/public
          target: /app/public
        - action: rebuild
          path: ./frontend/package.json
    environment:
      NODE_ENV: development